name: Aktist
favicon: null
layout_spectrum: 0.28755693417042494
typography_spectrum: 0.5888494895771146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8926491162274033
  lightness: 0.3595435628667474
  saturation: 0.17533182306215167
  rhythmicContrast: 0.7863200206775218
purpose: []
